### ISSUE TITLE
[12oc] Challenge selector not disappearing after clicking actively selected year

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/Mesures-Website#10]
I don't really know how to describe it so here are screenshots.

![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/b5b291eb-18bf-4c28-b436-ca94d770b6d1)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/e0204dbd-0526-44d7-8195-7ef5e631a238)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/ad8649bb-4bb6-4726-8c26-2938b1269451)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/b4d009bf-611f-441c-8681-b3ee227125c5)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/75f4b23d-eb82-4310-ad01-2b205639d44c)

**Comment by BeepBot99** [comment]
Yeah I changed some of the logic for that sorry I forgot to write it down somewhere that I did it.
Just in the `yearSelect()` function, `if (year == syearActive)`, (which already exists), just give `#select-challenge` the `noDisplay` class.

**Comment by BeepBot99** [comment]
I can do it right now if you want.
It's only a single line of code that needs to be added.
By the way, if you click on the active month while the challenge select menu is open, check to make sure that the challenge select menu goes away.

**Comment by Mesure73L** [comment]
I will do it

**Comment by Mesure73L** [comment]
Everything else works fine, it’s just that one problem

**Comment by BeepBot99** [comment]
Okay, great!

**Comment by Mesure73L** [comment]
Bug should be fixed, still needs testing

**Comment by Mesure73L** [comment]
Bug fixed + tested
