### ISSUE TITLE
User needs to clear cache whenever files are referenced

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/Mesures-Website#13]
Just thought I'd put this in issues, but every time any referenced file is edited the user is required to clear cache.

**Comment by Mesure73L** [comment]
@BeepBot99 you can self assign this if you want

**Comment by BeepBot99** [comment]
OK, I'll work on it.

**Comment by Mesure73L** [comment]
Ok, thanks

**Comment by Mesure73L** [comment]
If there's a way to make it automatic that would be nice (assuming you're using `?n=1`)

**Comment by BeepBot99** [comment]
Since I am doing settings, can you please do this?
If not, it's fine though.

**Comment by Mesure73L** [comment]
I'll try

**Comment by BeepBot99** [comment]
OK, thank you!

**Comment by Mesure73L** [comment]
Would this work?
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/3d363ccf-1f14-4046-ac4a-11f754207bdf)

**Comment by Mesure73L** [comment]
I think it's fixed, it just needs testing

**Comment by BeepBot99** [comment]
What did you do to fix it?

**Comment by BeepBot99** [comment]
Oh I see.
That will not work.
`.htaccess` only works for Apache web servers.

**Comment by BeepBot99** [comment]
I would not disable caching.
It can have bad long term effects.
In Chrome and Edge, you can go to `Developer Tools --> Network --> Disable Caching`, which will disable caching for a single website.
However, I know that you are not able to access developer tools at school.
So, you can disable caching now, but I would highly encourage that you enable it when your website is done.
Then, every time you change the `CSS` or `JS`, just **manually** increment the `?n=` parameter by 1. That way, the browser will only un-cache when there is an update to the website.

**Comment by BeepBot99** [comment]
> Oh I see. 
That will not work. `.htaccess` only works for Apache web servers.

Sorry about that, I was wrong.
`.htaccess` does only work in Apache servers, but I did not know that x10hosting used Apache.
So, it will (probably) work, but I would still **highly encourage** that you remove it after website development is finished.

**Comment by Mesure73L** [comment]
> Oh I see. That will not work. `.htaccess` only works for Apache web servers.

I believe it is Apache

**Comment by Mesure73L** [comment]
oh I didnt see your other messages

**Comment by Mesure73L** [comment]
Fixed, the `?n=...` parameter is already in all of the files, but for now it won't cache anything for the user
