### ISSUE TITLE
Need To Create A Class To Manage Cookies

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#16]
I am creating a class to manage cookies. It will be accessible by `Cookies`. You will be able to do a few things with it. For example, you can do `Cookies.completed=` to set completed. When you set the variable `Cookies.completed`, it will run the `setCookie()` function for you with the correct parameters. You will also be able to reference `Cookies.completed` and it will run `getCookie()` for you. In addition, it will have a `Cookies.completeChallenge()` function.

**Comment by BeepBot99** [comment]
This has been completed, but I still need to implement it into the code.

**Comment by BeepBot99** [comment]
Since a lot of the functions are different now, I think it would be better if

1. I make the settings.
2. @Mesure73L makes the settings, but starts all over on it.
I have completed everything except for settings.

**Comment by Mesure73L** [comment]
> Since a lot of the functions are different now, I think it would be better if
> 
> 1. I make the settings.
> 2. @Mesure73L makes the settings, but starts all over with it.
>    I have completed everything except for settings.

1

**Comment by Mesure73L** [comment]
Can this issue be closed?

**Comment by BeepBot99** [comment]
No, it will stay open until it is done.

**Comment by Mesure73L** [comment]
I thought you finished it already

**Comment by BeepBot99** [comment]
No, I still need to implement it.
However, I do realize now that that can be discussed in the PR for it.
