### ISSUE TITLE
[IDEA] Naming scheme

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#22]
**If your idea is related to a problem you had, what is it?**
`print("m"+"i"+"n"+"y"+"streem")`

**Describe the solution you'd like**
Never change the name of 12oc

**Describes alternatives**
Kill Minystreem

**Additional context**
Nothing

**Comment by Mesure73L** [comment]
Locking conversation for... violence?

**Comment by Mesure73L** [comment]
Elaborating, the won't fix is for your alternative solution, not the first one
