### ISSUE TITLE
[IDEA] Use the 12oc logo

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#28]
**If your idea is related to a problem you had, what is it?**
I made a perfectly good logo for 12oc and it's not being used.

**Describe the solution you'd like**
Used in places other than the favicon. In the favicon, you can barely actually see the content of the logo.

**Describes alternatives**
Not use it.

**Comment by BeepBot99** [comment]
> Have you seen the favicon?

Please read the rest of the message before responding.
> Where would it go that would actually look good?

I was thinking of some scroll-based animation, I'll figure it out.

**Comment by Mesure73L** [comment]
Fine, I'll use the 12oC logo.
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/7635ee94-4178-4834-b75b-a7d2c812f691)
Happy now?

**Comment by BeepBot99** [comment]
YKWIM.

**Comment by BeepBot99** [comment]
Maybe a twelve-of-code/about page?

**Comment by Mesure73L** [comment]
> Maybe a twelve-of-code/about page?

I want the Twelve of Code user experience to be a one-page experience. You can add an [About] button next to the [Settings] button and use it, if you want, but make sure it looks good.

**Comment by BeepBot99** [comment]
You can close this issue if you don't want the logo shown.
You can also assign this to you instead if you want to do it instead of me.

**Comment by Mesure73L** [comment]
Whatever you want

**Comment by Mesure73L** [comment]
I'm closing this for now, if I want it I'll reopen it
