### ISSUE TITLE
Add Pros and Cons to Feature Request Issue Template

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#29]
### What problem were you having?

I added them on one issue, and I think it is a nice addition.

### What solution would you like?

Add a list of three pros and three cons to the feature request issues template.

### What alternatives have you considered?

Only doing pros

**Comment by BeepBot99** [comment]
Oh that looks bad
The *No response* does.

**Comment by Mesure73L** [comment]
Overall, suggestion accepted. I will add that.

> Oh that looks bad The _No response_ does.

Unfortunately that's how GitHub does it and there is no way to customize that

**Comment by BeepBot99** [comment]
No, this is not completed.
![image](https://github.com/Mesure73L/Mesures-Website/assets/74377508/6902ca9a-c9fa-44c3-b5fa-a77bdb97bfcf)

**Comment by Mesure73L** [comment]
I already saw that and fixed it.
