### ISSUE TITLE
Buttons for data in 12oc

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#30]
### What problem were you having?

1. It is not clear what the data is for unless you know
2. It would be easier to program

### What solution would you like?

Add an `Export Data` button and an `Import Data` button.
Each will bring up a modal, made by SweetAlert2.
The `Export Data` button will have a `disabled` textarea where you can copy from.
It will also have a button to download a `.txt` file.
The `Import Data` button will have an empty textarea with a placeholder of `Paste your data here`.
It will also have a place to either select or drag and drop a `.txt` file.

### What alternatives have you considered?

Leaving it as it currently is, where it is unclear what data is for.
If I did this, then I would also have to completely delete and rewrite the code to get it to work.
(I would have to do that too if I did this though.)

### What page is this for?

twelve of code

**Comment by BeepBot99** [comment]
Is there a way to make the "What page is this for?" input not go into the issue but instead as a label?

**Comment by Mesure73L** [comment]
If you want to make that then sure.

> Is there a way to make the "What page is this for?" input not go into the issue but instead as a label? I just removed it because it is ugly.

No, I checked. I will be adding it back, however

**Comment by BeepBot99** [comment]
No, I removed it from this issue, not the template.

**Comment by Mesure73L** [comment]
very useful information, github
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/d29a69b2-0b42-409a-9d82-35c661a7e236)

**Comment by Mesure73L** [comment]
> No, I removed it from this issue, not the template.

I told you I would add it back

**Comment by BeepBot99** [comment]
https://github.com/Mesure73L/Mesures-Website/discussions/31
