### ISSUE TITLE
12oC challenge selector keeps challenge active after making the month unset

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/Mesures-Website#32]
### What happened?

I clicked 2023 for the year, December for the month, and then Challenge 2 (although I don't think any of those selections matter, that's just what I chose).

Nothing was wrong until I clicked December again to disable it, and then I clicked it a third time. Challenge 2 was still appearing active even though it shouldn't be. (The challenge itself didn't appear, but the button was still appearing as active. Also, the JavaScript knew it shouldn't be active, just a visual glitch that should be fixed.)

### What did you expect to happen?

I expected the challenge to not be appearing as active, because it wasn't active and shouldn't be active.

### What page was this on?

twelve of code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

### Other notes

I'll give screenshots of what I did.

![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/2f6414d6-b4ae-473d-a331-d6dd231b3454)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/e37d2282-3721-42a0-9d0a-500f020d22c6)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/ed0ebc25-9bbe-4e92-9056-32d5bdeae828)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/0f5235b7-4983-4f1f-b643-ece9a0951120)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/a4b88200-feba-4235-a06d-878f6b509e7d)
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/38213575-c2de-478d-9c47-c744597ae697)

**Comment by Mesure73L** [comment]
I want to fix this to help myself understand the logic used in the new `twelve-of-code/script.js`, even if it would be faster for you to fix this.

**Comment by BeepBot99** [comment]
Just letting you know, I am currently working on something in script.js. It might be easier if you do it later to avoid merge conflicts.
I am currently only working in the settings section of the code, so if you do decide to do it now, please do not change anything there.

**Comment by Mesure73L** [comment]
> Just letting you know, I am currently working on something in script.js. It might be easier if you do it later to avoid merge conflicts. I am currently only working in the settings section of the code, so if you do decide to do it now, please do not change anything there.

I will wait until you are done, let me know when I can create a new branch to fix this bug.

**Comment by BeepBot99** [comment]
You can work on this now.
