### ISSUE TITLE
Twelve of Code doesn't fully work using GitHub codespaces

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/Mesures-Website#37]
### What happened?

I am trying to work on the system for the actual challenges, and the challenge just doesn't load (I'm using GitHub codespaces as that's pretty much my only option). I selected 2023 > december > 1, which is the challenge I'm currently using for development, and it just won't load.

### What did you expect to happen?

I expected it to load the challenge, especially after I changed it from referencing `"https://mesure.x10.mx/twelve-of-code/not-an-api/challenges/2023/dec/1.html"` to `"./not-an-api/challenges/2023/dec/1.html"`.

### What page was this on?

twelve of code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

### Enter logs

I don't have access to console because I'm in school, I'll update this when I get home if I remember

**Comment by Mesure73L** [comment]
I'm working in the `12oc-creating-challenges` branch if that matters

**Comment by BeepBot99** [comment]
How are you previewing your website?
With `./not-an-api/challenges/2023/dec/1.html`, it may be referring to the file on Github's servers where the code is run.

**Comment by Mesure73L** [comment]
> How are you previewing your website? With `./not-an-api/challenges/2023/dec/1.html`, it may be referring to the file on Github's servers where the code is run.

I'm using `http-server` in GH Codespaces (which starts a static server showing the website, using codespace's servers)

**Comment by BeepBot99** [comment]
Fixing issue #38 will also fix this, so I am assigning you.

**Comment by Mesure73L** [comment]
for some reason this just fixed itself???
