### ISSUE TITLE
Remove <!DOCTYPE html> from challenge html files

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#38]
### What problem were you having?

IE less than version 11 will not load the page if there are two DOCTYPE declarations.

### What solution would you like?

Remove the `<!DOCTYPE html>` declaration and the `<body>` tag.

### What alternatives have you considered?

Using an `iframe` to display the challenges.
That might actually be better in some ways.

#### Pros
* Internet Explorer can load the page
#### Cons
* **UGGGH SO MUCH WORK TO DELETE ONE LINE OF CODE!!!!!**

### What page is this for?

twelve of code

**Comment by BeepBot99** [comment]
If you use an `iframe`, then you can load any page even if it's cross-origin, so that would probably fix issue https://github.com/Mesure73L/Mesures-Website/issues/37 too.

**Comment by Mesure73L** [comment]
also just telling you now the question titles are h2 (##) so if you want a heading instead of bold for it you should use h3 (###) instead of h1 (#)

**Comment by BeepBot99** [comment]
> also just telling you now the question titles are h2 (##) so if you want a heading instead of bold for it you should use h3 (###) instead of h1 (#)

No, the question titles are h3 now (###) so i used h4 (####).

**Comment by BeepBot99** [comment]
So are you just removing the `<!DOCTYPE html>` declaration or are you making it an `iframe`?
Note that if you make it an `iframe`, then keep the  `<!DOCTYPE html>` declaration and also add a `<head>`.

**Comment by BeepBot99** [comment]
LOL, you assigned me and then realized that you are not a lazy person and assigned yourself instead.
You also might have realized that you asked me to stop development soon.

**Comment by Mesure73L** [comment]
> LOL, you assigned me and then realized that you are not a lazy person and assigned yourself instead. You might have also realized that you asked me to stop development soon.

no, i just wanted to make it so im not bored 24/7

**Comment by BeepBot99** [comment]
> > So are you just removing the `<!DOCTYPE html>` declaration or are you making it an `iframe`? Note that if you make it an `iframe`, then keep the `<!DOCTYPE html>` declaration and also add a `<head>`.
> 
> iframe

Are you going to do it or should I?
It will only take a few minutes to do.

**Comment by BeepBot99** [comment]
OK.

**Comment by BeepBot99** [comment]
@Mesure73L What if you created a modal with the challenge in it?

**Comment by Mesure73L** [comment]
## Pros and cons of using iframe

### Pros:

- Easier to fix #37 
- uhhhh someone help me out here

### Cons:

- Slower (by a LOT)
- Makes it harder to do some of my future plans
- and probably some more

@BeepBot99 what do you think?

**Comment by BeepBot99** [comment]
About the second pro:
What does that mean?
About the first con:
No, there is no significant difference.
About the second con:
What are they?

**Comment by BeepBot99** [comment]
Why do you think iframes make it slower?
All it is doing is sending an XHTTP request, which is what you are already doing.

**Comment by Mesure73L** [comment]
> No, there is no significant difference.

Yes, there is. I have it open [here](https://verbose-lamp-v94p54jg6943pw67-8080.app.github.dev/mesure.x10.mx/private_html/twelve-of-code/) temporarily

> About the second con:
> What are they?

Challenge verifiers, idk some other stuff

**Comment by BeepBot99** [comment]
Well it is slower because it's in GH codespaces.
It won't actually be slower on the website.
Also, GHCS is blocked in my school so I can't view it.

**Comment by Mesure73L** [comment]
> Well it is slower because it's in GH codespaces. It won't actually be slower on the website. Also, GHCS is blocked in my school so I can't view it.

...
JSYK, I tried the old one before this and it was **WAY FASTER**. It being GHCS does not make a difference

**Comment by Mesure73L** [comment]
It's not slower because of the information it's getting, it's slower because of how it's displaying that information.

**Comment by Mesure73L** [comment]
An alternative is to say "Challenge is loading, please wait" or something like that while it's loading

**Comment by Mesure73L** [comment]
@BeepBot99 I think the current method is better, I'll remove `<!DOCTYPE html>` and `<body>` elements if you think thats better

**Comment by Mesure73L** [comment]
Moving to pull request, #39
