### ISSUE TITLE
GithHub Label for Maybe

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#44]
### What problem were you having?

There was no label for what I wanted to say.

### What solution would you like?

A label for if something may be done later, or it may not be done, but it is not important.
This is kind of the same as `low priority`, but it should fit in with `planned`, `in progress`, and `paused`.

### What alternatives have you considered?

Just use `low priority` for this.

### What are some pros and cons of doing this?

**Pro:** It makes it easier to classify issues and pull requests.
**Con:** I can't think of a name for it.

**Comment by Mesure73L** [comment]
GitHub*

but anyways it’s created now (pending)
