### ISSUE TITLE
My school blocks x10hosting

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#5]
This isn't actually a problem, there's no way to fix this, I'm just creating this issue to talk here.

**Comment by Mesure73L** [comment]
Unfortunately there is no way to fix this until I get a domain for the website

**Comment by BeepBot99** [comment]
No, it's not the domain.
It's that the `x10hosting` servers are blocked.
There is no way to fix this other than hosting it on different servers.
