### ISSUE TITLE
Github Action pushes all branches to FTP server, not just main

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/Mesures-Website#6]
This is a really important problem and needs to be fixed immediately. If you are testing something in another branch, when you commit it, it will push that branch to the website.

**Comment by BeepBot99** [comment]
This is been fixed but still needs testing to ensure that it has worked.

**Comment by Mesure73L** [comment]
Just checking, is this supposed to happen?
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/8fa2e49e-5750-47e5-8a7b-a9294c968301)

**Comment by BeepBot99** [comment]
It has been fixed.
# Explanation
I copied the code for preventing it in all other branches from StackOverflow. Using `git` on desktop, the default name for the main branch is `master`. However, on GitHub, it is `main`. The code I used prevented the action from running in all other branches than `master`, which doesn't exist. What I wanted was to prevent it from running in all branches other than `main`. I have changed and tested it. It is now working as intended.
